application: jfkwizard
version: 6
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /colophon
  static_files: static/colophon.html
  upload: static/colophon.html
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /.*
  script: jfkwizard.application